### PR TITLE
Add Cluster class

### PR DESCRIPTION
**Pull request by fchinu**

### CODE REVIEW

**Review by Roberta-Ferioli — APPROVED** [review]
Thank you @fchinu, it's ok for me. As your request I don't merge it yet

**Comment by GiorgioAlbertoLucia** [comment]
It looks fine. The maximum cluster size we are currently accepting is 64 (8x8), so I guess there is no reason to have fClusterSize bigger than a uint8_t (we could even define a 6 bit integer, but I guess it is not worth it). The constant MAX_CLUSTER_SIZE is misleading, I think. That number is the maximum size of the array, which is related to the cluster size, but not exactly it. Something along the lines of MAX_CLUSTER_ROWS is probably better (we can also add a commento on the side to specify what is its purpose).

Edit: I found another issue: fMeanX and Y should be double, as the position of the cluster could be between two pixels.

**Comment by Roberta-Ferioli** [comment]
Just one more things. Maybe we need errors on x-mean and y-mean, so I would add these two attributes

**Comment by fchinu** [comment]
Thank you for your suggestions @GiorgioAlbertoLucia @Roberta-Ferioli! I have implemented them. I have a doubt regarding the errors, in the sense that error is given by pitch/sqrt(12), so I don't know if we really want this "real measure" in the cluster class. I would prefer to keep it "pixel-wise", but I can implement it if you prefer

**Comment by GiorgioAlbertoLucia** [comment]
I would also add a constructor that takes as input fMeanX, fMeanY and fClusterSize. These quantities are already evaluated in the clustering algorithm, so there is no point in doping it again (I would leave the other constructor as well, it might be useful in the future).

For the sake of consistency, would you prefer to have #pragma once on top instradamento of #ifndef ...?

**Comment by Roberta-Ferioli** [comment]
> Thank you for your suggestions @GiorgioAlbertoLucia @Roberta-Ferioli! I have implemented them. I have a doubt regarding the errors, in the sense that error is given by pitch/sqrt(12), so I don't know if we really want this "real measure" in the cluster class. I would prefer to keep it "pixel-wise", but I can implement it if you prefer.

Thank you a lot @fchinu, now I have a doubt, we take the mean on x and y as the hit position for tracking. Is the error pitch/sqrt(12) or semi-dispersion on the positions? We can discuss. Usually is used pitch/sqrt(12), but our mean can be on a pixel that is not lit and is not part of the cluster. Is it the same?

**Comment by GiorgioAlbertoLucia** [comment]
Please change fChipId to fChipID. (in general Id -> ID). We are civilized

**Pull request merged**
